#include<iostream>
using namespace std;
int main()
{
	int i,j,a[9][9],x,y,count1,count2,m,c,d,count,n,b[9],p,q;
	cout<<"Enter the sudoku to be solved: \n";
	for(i=0;i<9;i++)
	for(j=0;j<9;j++)
	cin>>a[i][j];
	for(i=0;i<9;i++)
	b[i]=0;
	while(1)
	{
		for(j=0;j<9;j++)
		for(i=0;i<9;i++)
		{
			if(a[i][j]!=0)
			{
				if(j==0||j==3||j==6)
				{
					x=j+1;
					y=j+2;
				}
				else if(j==1||j==4||j==7)
				{
					x=j+1;
					y=j-1;
				}
				else
				{
					x=j-1;
					y=j-2;
				}
				count1=-1;
				count2=-1;
				for(m=0;m<9;m++)
				if(a[i][j]==a[m][x])
				{
					count1=m;
					break;	
				}
				for(m=0;m<9;m++)
				if(a[i][j]==a[m][y])
				{
					count2=m;
					break;
				}
				c=-1;
				if((count1!=-1&&count2==-1)||(count1==-1&&count2!=-1))
				{
					if(count1!=-1)
					{
						c=y;
						d=count1;
					}
					else
					{
						c=x;
						d=count2;
					}
					if((i==0||i==1||i==2)&&(d==3||d==4||d==5))
					d=6;
					else if((i==0||i==1||i==2)&&(d==6||d==7||d==8))
					d=3;
					else if((i==3||i==4||i==5)&&(d==0||d==1||d==2))
					d=6;
					else if((i==3||i==4||i==5)&&(d==6||d==7||d==8))
					d=0;
					else if((i==6||i==7||i==8)&&(d==0||d==1||d==2))
					d=3;
					else
					d=0;
					for(m=d;m<=d+2;m++)
					{
						if(a[m][c]==0)
						{
							if(m==0||m==3||m==6)
							{
								x=m+1;
								y=m+2;
							}
							else if(m==1||m==4||m==7)
							{
								x=m+1;
								y=m-1;
							}
							else
							{
								x=m-1;
								y=m-2;
							}
							count=0;
							for(n=0;n<9;n++)
							if(a[x][n]==a[i][j])
							break;
							else
							count++;
							if(count!=9||a[x][c]!=0)
							{
								count=0;
								for(n=0;n<9;n++)
								if(a[y][n]==a[i][j])
								break;
								else
								count++;
								if(count!=9||a[y][c]!=0)
							    {
									a[m][c]=a[i][j];
									break;
								}
							}
						}
					}
				}	
			}
		}
		for(i=0;i<9;i++)
		for(j=0;j<9;j++)
		{
			if(a[i][j]!=0)
			{
				if(i==0||i==3||i==6)
				{
					x=i+1;
					y=i+2;
				}
				else if(i==1||i==4||i==7)
				{
					x=i+1;
					y=i-1;
				}
				else
				{
					x=i-1;
					y=i-2;
				}
				count1=-1;
				count2=-1;
				for(m=0;m<9;m++)
				if(a[i][j]==a[x][m])
				{
					count1=m;
					break;	
				}
				for(m=0;m<9;m++)
				if(a[i][j]==a[y][m])
				{
					count2=m;
					break;
				}
				c=-1;
				if((count1!=-1&&count2==-1)||(count1==-1&&count2!=-1))
				{
					if(count1!=-1)
					{
						c=y;
						d=count1;
					}
					else
					{
						c=x;
						d=count2;
					}
					if((j==0||j==1||j==2)&&(d==3||d==4||d==5))
					d=6;
					else if((j==0||j==1||j==2)&&(d==6||d==7||d==8))
					d=3;
					else if((j==3||j==4||j==5)&&(d==0||d==1||d==2))
					d=6;
					else if((j==3||j==4||j==5)&&(d==6||d==7||d==8))
					d=0;
					else if((j==6||j==7||j==8)&&(d==0||d==1||d==2))
					d=3;
					else
					d=0;
					for(m=d;m<=d+2;m++)
					{
						if(a[c][m]==0)
						{
							if(m==0||m==3||m==6)
							{
								x=m+1;
								y=m+2;
							}
							else if(m==1||m==4||m==7)
							{
								x=m+1;
								y=m-1;
							}
							else
							{
								x=m-1;
								y=m-2;
							}
							count=0;
							for(n=0;n<9;n++)
							if(a[n][x]==a[i][j])
							break;
							else
							count++;
							if(count!=9||a[c][x]!=0)
							{
								count=0;
								for(n=0;n<9;n++)
								if(a[n][y]==a[i][j])
								break;
								else
								count++;
								if(count!=9||a[c][y]!=0)
								{
									a[c][m]=a[i][j];
									break;
								}
							}
						}
					}
				}	
			}
		}
		for(i=0;i<9;i++)
		{
			count=0;
			for(j=0;j<9;j++)
			{
				if(a[i][j]==0)
				{
					count++;
					x=j;
				}
				else
				b[a[i][j]-1]=1;
			}
			if(count==1)
			for(m=0;m<9;m++)
			if(b[m]==0)
			{
				a[i][x]=m+1;
				break;
			}	
			for(m=0;m<9;m++)
			b[m]=0;
		}
		for(j=0;j<9;j++)
		{
			count=0;
			for(i=0;i<9;i++)
			{
				if(a[i][j]==0)
				{
					count++;
					x=i;
				}
				else
				b[a[i][j]-1]=1;
			}
			if(count==1)
			for(m=0;m<9;m++)
			if(b[m]==0)
			{
				a[x][j]=m+1;
				break;
			}	
			for(m=0;m<9;m++)
			b[m]=0;
		}
		x=0;
		y=0;
		for(m=0;m<9;m++)
		{
			count=0;
			if(m%3==0&&m!=0)
			{
				x=x+3;
				y=0;
			}
			for(i=x;i<=x+2;i++)
			for(j=y;j<=y+2;j++)
			{
				if(a[i][j]==0)
				{
					count++;
					p=i;
					q=j;
				}
				else
				b[a[i][j]-1]=1;
			}
			if(count==1)
			for(n=0;n<9;n++)
			if(b[n]==0)
			{
				a[p][q]=n+1;
				break;
			}
			for(n=0;n<9;n++)
			b[n]=0;
			y=y+3;
		}
		count=0;
		for(i=0;i<9;i++)
		for(j=0;j<9;j++)
		if(a[i][j]==0)
		{
			count++;
			break;
		}
		if(count==0)
		goto g;
	}
	g:
	{
		cout<<"The answer is: \n";
		for(i=0;i<9;i++)
		{
			if(i%3==0)
			cout<<"\n";
			for(j=0;j<9;j++)
			{
				if(j%3==0)
				cout<<" ";
				cout<<a[i][j];
			}
			cout<<"\n";
		}
	}
}
